baseURL: https://sayakan.github.io/blog/
publishDir: "docs"
theme: "PaperMod"
paginate: 5
canonifyurls: false

title: In step with the times

enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
        - name: Archive
          url: archives
          weight: 10
        - name: Search
          url: search/
          weight: 15
        - name: Tags
          url: tags/
          weight: 20

params:

    title: "In step with the times"
    description: "Tech Blog of sayakan, a software engineer"
    author: Sayaka Nakagawa

    defaultTheme: auto

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    displayFullLangName: true
    ShowToc: true
    TocOpen: true
    comments: true
    ShareButtons: ["linkedin", "twitter", "facebook", "reddit", "whatsapp"]

    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...
    socialIcons:
      - name: github
        url: "https://github.com/sayakan"
      - name: twitter
        url: "https://twitter.com"
      - name: RSS
        url: "index.xml"

outputs:
  home:
    - HTML
    - RSS
    - JSON
    

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

